import Head from 'next/head'
import Country from "../components/country/Country"
import SearchInput from "../components/SearchInput/SearchInput";
import React, { useState } from "react";


export default function Home({countries}) {
  const [keyword, setKeyword] = useState('')
  const filteredCountries = countries.filter(country => 
    country.name.toLowerCase().includes(keyword) || country.region.toLowerCase().includes(keyword))
    console.log(countries);
  return (
    <div>
      <Head>
        <title>World Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchInput onChange = {(e) => setKeyword(e.target.value.toLowerCase())}/>
      <Country countries = {filteredCountries}/>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await  fetch('https://restcountries.eu/rest/v2/all');
  const countries = await res.json();
  return{
    props: {
      countries,
    }
  }
}
